name: re_1999_solidleaf
version: 1.0.0+1

environment:
  sdk: '^3.13.0'

dependencies:
  flutter:
    sdk: flutter
  archive: ^4.0.0
  dio: ^5.7.0
  dynamic_color: ^1.7.0
  flutter_colorpicker: ^1.1.0
  video_player: ^2.9.2
  file_picker: ^8.0.0
  fluentui_system_icons: ^1.1.231
  flutter_secure_storage: ^9.2.2
  path_provider: ^2.1.5
  path: ^1.9.0
  provider: ^6.1.2
  shared_preferences: ^2.3.1
  url_launcher: ^6.3.1
  window_manager: ^0.4.3
  audioplayers: ^6.0.0 # Актуальная версия пакета
  text_scroll: ^0.2.0
  squiggly_slider: ^1.0.5
  palette_generator: ^0.3.3+7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/launcher_icon.png"
  adaptive_icon_background: "assets/images/launcher_icon.png"
  adaptive_icon_foreground: "assets/images/launcher_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/music/
    - assets/images/music_cover/ # Папка, для фоновой музыки
    - assets/video/ # Папка для анимированной обложки (gif/webp)

